POST http://localhost:3000/products
Content-type: application/json

{
    "name": "",
    "price": -20.00
}

###
GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

###
PATCH http://localhost:3000/products/1
Content-type: application/json

{
    "price": 10.00
}

###
DELETE  http://localhost:3000/products/5
